## Please see https://smped.github.io/GRAVI/editing-yaml.html for a description of this file
# make comparison fc/fdr cutoffs really loose so that there are peaks for plotting
samples:
  file: "config/sample.txt"

paths:
  bam: "data/bam"

comparisons:
  method: "sq-lt"
  fc: 1
  fdr: 0.999
  paired: false
  filter_q: 0.6
  contrasts:
    - ["hCG", "PMSG"]
  ihw: "regions"

genome:
  build: "mm10"

external:
  blacklist: "data/external/mm10.blacklist.bed"
  gtf: "data/external/gencode.vM25.annotation.gtf"
  rnaseq: "data/external/limma_by_gene_8hvs0h.tsv"
  features:
  hic: "data/external/gc_loops.bedpe"
  coverage:

peaks:
  macs2:
    gsize: "mm"
    fdr: 0.05
    keep_duplicates: "all"
  qc:
    outlier_threshold: 10
    allow_zero: true
    min_prop_reps: 0.5

